#!/bin/sh
set -e
# Railway 等平台会注入 PORT；nginx 需监听该端口才能对外提供服务
PORT="${PORT:-3000}"
sed -i "s/listen 3000;/listen ${PORT};/" /etc/nginx/nginx.conf

# 运行时配置（docker run -e）；默认与 apps/web/.env.example 一致
VITE_API_BASE_URL="${VITE_API_BASE_URL:-http://localhost:8000}"
VITE_API_BASE_PATH="${VITE_API_BASE_PATH:-/api}"
VITE_WEB_BASE_URL="${VITE_WEB_BASE_URL:-http://localhost:3000}"
VITE_WEB_BASE_PATH="${VITE_WEB_BASE_PATH:-}"
VITE_ADMIN_BASE_URL="${VITE_ADMIN_BASE_URL:-http://localhost:3001}"
VITE_ADMIN_BASE_PATH="${VITE_ADMIN_BASE_PATH:-/god-mode}"
VITE_SPACE_BASE_URL="${VITE_SPACE_BASE_URL:-http://localhost:3002}"
VITE_SPACE_BASE_PATH="${VITE_SPACE_BASE_PATH:-/spaces}"
VITE_LIVE_BASE_URL="${VITE_LIVE_BASE_URL:-http://localhost:3100}"
VITE_LIVE_BASE_PATH="${VITE_LIVE_BASE_PATH:-/live}"
VITE_WEBSITE_URL="${VITE_WEBSITE_URL:-https://plane.so}"
VITE_SUPPORT_EMAIL="${VITE_SUPPORT_EMAIL:-support@plane.so}"
VITE_ENABLE_SESSION_RECORDER="${VITE_ENABLE_SESSION_RECORDER:-0}"
VITE_SESSION_RECORDER_KEY="${VITE_SESSION_RECORDER_KEY:-}"
# 不设则不在运行时注入上游仓库；请设置为你自己的 GitHub 仓库
VITE_GITHUB_STAR_URL="${VITE_GITHUB_STAR_URL:-}"
VITE_GITHUB_FORK_URL="${VITE_GITHUB_FORK_URL:-}"

{
  printf 'window.__PLANE_RUNTIME_CONFIG__ = '
  jq -n \
    --arg VITE_API_BASE_URL "$VITE_API_BASE_URL" \
    --arg VITE_API_BASE_PATH "$VITE_API_BASE_PATH" \
    --arg VITE_WEB_BASE_URL "$VITE_WEB_BASE_URL" \
    --arg VITE_WEB_BASE_PATH "$VITE_WEB_BASE_PATH" \
    --arg VITE_ADMIN_BASE_URL "$VITE_ADMIN_BASE_URL" \
    --arg VITE_ADMIN_BASE_PATH "$VITE_ADMIN_BASE_PATH" \
    --arg VITE_SPACE_BASE_URL "$VITE_SPACE_BASE_URL" \
    --arg VITE_SPACE_BASE_PATH "$VITE_SPACE_BASE_PATH" \
    --arg VITE_LIVE_BASE_URL "$VITE_LIVE_BASE_URL" \
    --arg VITE_LIVE_BASE_PATH "$VITE_LIVE_BASE_PATH" \
    --arg VITE_WEBSITE_URL "$VITE_WEBSITE_URL" \
    --arg VITE_SUPPORT_EMAIL "$VITE_SUPPORT_EMAIL" \
    --arg VITE_ENABLE_SESSION_RECORDER "$VITE_ENABLE_SESSION_RECORDER" \
    --arg VITE_SESSION_RECORDER_KEY "$VITE_SESSION_RECORDER_KEY" \
    --arg VITE_GITHUB_STAR_URL "$VITE_GITHUB_STAR_URL" \
    --arg VITE_GITHUB_FORK_URL "$VITE_GITHUB_FORK_URL" \
    '{
      VITE_API_BASE_URL: $VITE_API_BASE_URL,
      VITE_API_BASE_PATH: $VITE_API_BASE_PATH,
      VITE_WEB_BASE_URL: $VITE_WEB_BASE_URL,
      VITE_WEB_BASE_PATH: $VITE_WEB_BASE_PATH,
      VITE_ADMIN_BASE_URL: $VITE_ADMIN_BASE_URL,
      VITE_ADMIN_BASE_PATH: $VITE_ADMIN_BASE_PATH,
      VITE_SPACE_BASE_URL: $VITE_SPACE_BASE_URL,
      VITE_SPACE_BASE_PATH: $VITE_SPACE_BASE_PATH,
      VITE_LIVE_BASE_URL: $VITE_LIVE_BASE_URL,
      VITE_LIVE_BASE_PATH: $VITE_LIVE_BASE_PATH,
      VITE_WEBSITE_URL: $VITE_WEBSITE_URL,
      VITE_SUPPORT_EMAIL: $VITE_SUPPORT_EMAIL,
      VITE_ENABLE_SESSION_RECORDER: $VITE_ENABLE_SESSION_RECORDER,
      VITE_SESSION_RECORDER_KEY: $VITE_SESSION_RECORDER_KEY,
      VITE_GITHUB_STAR_URL: $VITE_GITHUB_STAR_URL,
      VITE_GITHUB_FORK_URL: $VITE_GITHUB_FORK_URL
    }'
  printf ';'
} > /usr/share/nginx/html/runtime-env.js

exec nginx -g "daemon off;"
